services:
    #nginx
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #php
    app:
        build:
            dockerfile: ./php/Dockerfile
            # target: app_dev
            target: "${BUILD_TARGET:-app}"
        volumes:
            - ./app:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            MYSQL_HOST: db # MySQL Host is what is defined under #mysql
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REDIS_HOST: cache # Redis Host is what is defined under #redis
            REDIS_PORT: ${REDIS_PORT}
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
          # Ensure that host.docker.internal is correctly defined on Linux
          - host.docker.internal:host-gateway
    #mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
    #redis
    cache:
        image: redis:latest

volumes:
    mysqldata:
